app/urls.py
from django.urls import path


from . import views

app_name = "myapp"

urlpatterns = [
    path("", views.index, name="index"),
    path("trend", views.trend, name="trend"),
    path("Dashboard/", views.Dash, name="Dash"),
    path("Privacy/", views.Privacy, name="Privacy"),
    path("my_ads/", views.my_ads, name="my_ads"),
    path("edit/<int:pk>/", views.product_edit, name="product_edit"),
    path("delete/<int:pk>/", views.product_delete, name="product_delete"),
    path("Profile/", views.Profile, name="Profile"),
    path("payment/", views.payment, name="payment"),
    path("shopgrid", views.product_list, name="shopgrid"),
    path("success/", views.success, name="success"),
    path("shopdetails/<int:product_id>/", views.product_detail, name="product_detail"),
    path("create/", views.product_create, name="product_create"),
    path("cart/", views.cart, name="cart"),
    path("add_to_cart/<int:product_id>/", views.add_to_cart, name="add_to_cart"),
    path("checkout/", views.checkout, name="checkout"),
    path("contact", views.contact, name="contact"),
    path("categories/", views.CategoryListView.as_view(), name="category-list"),
    path(
        "subcategories/", views.SubcategoryListView.as_view(), name="subcategory-list"
    ),
    path(
        "subcategories/<int:category_id>/",
        views.SubcategoryListView.as_view(),
        name="subcategory-list-with-category",
    ),
    path("products/", views.ProductListView.as_view(), name="product-list"),
    path(
        "products/<int:category_id>/<int:subcategory_id>/",
        views.ProductListView.as_view(),
        name="product-list-with-category-subcategory",
    ),
]

core/urls.py
import os
from dotenv import load_dotenv
from django.contrib import admin
from django.urls import include, path, re_path
from django.conf import settings
from django.conf.urls.static import static
from users.views import CustomLoginView, ResetPasswordView, ChangePasswordView
from django.contrib.auth import views as auth_views
from users.forms import LoginForm

load_dotenv()

adminPath = os.getenv('ADMIN_PATH')
if(adminPath == None):
    adminPath = 'admin'


urlpatterns = [
    path("", include("app.urls")),
    path(f"{adminPath}/", admin.site.urls),
    path("accounts/", include("users.urls")),
    path(
        "login/",
        CustomLoginView.as_view(
            redirect_authenticated_user=True,
            template_name="login.html",
            authentication_form=LoginForm,
        ),
        name="login",
    ),
    path(
        "logout/",
        auth_views.LogoutView.as_view(template_name="users/logout.html"),
        name="logout",
    ),
    path("password-reset/", ResetPasswordView.as_view(), name="password_reset"),
    path(
        "password-reset-confirm/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="users/password_reset_confirm.html"
        ),
        name="password_reset_confirm",
    ),
    path(
        "password-reset-complete/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="users/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
    path("password-change/", ChangePasswordView.as_view(), name="password_change"),
    re_path(r"^oauth/", include("social_django.urls", namespace="social")),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %} {% endblock %}</title>

    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/bootstrap.min.css' %}">

    <link rel="stylesheet" type="text/css" href="{% static 'assets/fonts/line-icons.css' %}">

    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/slicknav.css' %}">

    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/color-switcher.css' %}">

    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/animate.css' %}">

    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/owl.carousel.css' %}">

    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/main.css' %}">

    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/responsive.css' %}">
</head>


{% block content %} {% endblock %}


<footer>

    <section class="footer-Content">
        <div class="container">
            <div class="row">
                <div class="col-lg-4 col-md-4 col-xs-6 col-mb-12">
                    <div class="widget">
                        <div class="footer-logo"><img src="{% static 'assets/img/logo1.png' %}" alt=""
                                style="width: 300px; height: 75px;"></div>
                        <div class="textwidget">
                            <p>Giyaa Commerce is an e-commerce platform that is used by businesses of all sizes around
                                the world. It offers a wide range
                                of features, including online stores, product management, marketing tools, and more.
                                Giyaa Commerce has a presence in
                                Ethiopia, and there are a number of Ethiopian businesses that use it to sell their
                                products online.</p>
                        </div>
                        <ul class="mt-3 footer-social">
                            <li><a class="facebook" href="#"><i class="lni-facebook-filled"></i></a></li>
                            <li><a class="twitter" href="#"><i class="lni-twitter-filled"></i></a></li>
                            <li><a class="linkedin" href="#"><i class="lni-linkedin-fill"></i></a></li>
                            <li><a class="google-plus" href="#"><i class="lni-google-plus"></i></a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-4 col-md-4 col-xs-6 col-mb-12">
                    <div class="widget">
                        <h3 class="block-title">Quick Link</h3>
                        <ul class="menu">
                            <li><a href="/">- About Us</a></li>
                            <li><a href="{% url 'login' %}">- Login</a></li>
                            <li><a href="{% url 'myapp:shopgrid' %}">- Shop</a></li>
                            <li><a href="{% url 'users-register' %}">- Register</a></li>
                            <li><a href="{% url 'myapp:contact' %}">- FAQ's</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-4 col-md-4 col-xs-6 col-mb-12">
                    <div class="widget">
                        <h3 class="block-title">Contact Info</h3>
                        <ul class="contact-footer">
                            <li>
                                <strong><i class="lni-phone"></i></strong><span>+251987654321 <br> +251987654321 </span>
                            </li>
                            <li>
                                <strong><i class="lni-envelope"></i></strong>
                                <span>
                                    <a href="#" class="__cf_email__"></a>support@giyaamarket.com</a>
                                </span>

                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </section>


    <div id="copyright">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="site-info text-center">
                        <p><a target="_blank" href="#">Hammer Tech</a></p>
                    </div>
                </div>
            </div>
        </div>
    </div>

</footer>


<a href="#" class="back-to-top">
    <i class="lni-chevron-up"></i>
</a>

<!-- <div id="preloader">
    <div class="loader" id="loader-1"></div>
</div> -->


<script data-cfasync="false"
    src="{% static 'cdn-cgi/scripts/5c5dd728/cloudflare-static/email-decode.min.js' %}"></script>
<script src="{% static 'assets/js/jquery-min.js' %}"></script>
<script src="{% static 'assets/js/popper.min.js' %}"></script>
<script src="{% static 'assets/js/bootstrap.min.js' %}"></script>
<script src="{% static 'assets/js/jquery.counterup.min.js' %}"></script>
<script src="{% static 'assets/js/waypoints.min.js' %}"></script>
<script src="{% static 'assets/js/wow.js' %}"></script>
<script src="{% static 'assets/js/owl.carousel.min.js' %}"></script>
<script src="{% static 'assets/js/jquery.slicknav.js' %}"></script>
<script src="{% static 'assets/js/main.js' %}"></script>
<script src="{% static 'assets/js/form-validator.min.js' %}"></script>
<script src="{% static 'assets/js/contact-form-script.min.js' %}"></script>
<script src="{% static 'assets/js/summernote.js' %}"></script>
</body>


</html>

templates/category_detail.html
{% extends "base.html" %}

{% load static %}

{% block title %}Categories List{% endblock %}


{% block content %}


<!-- Product Section Begin -->
<section class="product spad">
    <div class="container">
        <div class="row">
            <div class="col-lg-3 col-md-5">
                <div class="sidebar">
                </div>
            </div>
        </div>
        <div class="col-lg-9 col-md-7">
            <div class="product__discount">
                <div class="section-title product__discount__title">
                    <h2>{{ category.name }}</h2>
                </div>
                <div class="row">
                    <div class="product__discount__slider owl-carousel">
                        {% for product in products %}
                        <div class="col-lg-4">
                            <div class="product__discount__item">
                                <div class="product__discount__item__pic set-bg" data-setbg="{{ product.image1.url }}">
                                    {% if sale and product.discount_price %}
                                    <div class="product__discount__percent">-10%</div>
                                    {% endif %}
                                    <ul class="product__item__pic__hover">
                                        <li><a href="#"><i class="fa fa-heart"></i></a></li>
                                        <li><a href="#"><i class="fa fa-retweet"></i></a></li>
                                        <li><a href="{% url 'myapp:add_to_cart' product.id %}"><i
                                                    class="fa fa-shopping-cart"></i></a></li>
                                    </ul>
                                </div>
                                <div class="product__discount__item__text">
                                    <span>{{ product.category }}</span>
                                    <h5><a href="{% url 'myapp:product_detail' product.id %}">{{ product.title }}</a>
                                    </h5>
                                    <div class="product__item__price">ETB{{ product.price }}
                                        {% if sale and product.discount_price %}
                                        <span>ETB{{ product.discount_price }}</span>
                                        {% endif %}
                                    </div>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
            <div class="filter__item">
                <div class="row">
                    <div class="col-lg-4 col-md-5">
                        <div class="filter__sort">
                            <span>Sort By</span>
                            <select>
                                <option value="0">Default</option>
                                <option value="0">Default</option>
                            </select>
                        </div>
                    </div>
                    <div class="col-lg-4 col-md-4">
                        <div class="filter__found">
                            <h6><span>16</span> Products found</h6>
                        </div>
                    </div>
                    <div class="col-lg-4 col-md-3">
                        <div class="filter__option">
                            <span class="icon_grid-2x2"></span>
                            <span class="icon_ul"></span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                {% for product in products %}
                <div class="col-lg-4 col-md-6 col-sm-6">
                    <div class="product__item">
                        <div class="product__item__pic set-bg" data-setbg="{{ product.image1.url }}">
                            <ul class="product__item__pic__hover">
                                <li><a href="#"><i class="fa fa-heart"></i></a></li>
                                <li><a href="#"><i class="fa fa-retweet"></i></a></li>
                                <li><a href=""><i class="fa fa-shopping-cart"></i></a></li>
                            </ul>
                        </div>
                        <div class="product__item__text">
                            <h6><a href="#">{{ product.title }}</a></h6>
                            <h5>ETB{{ product.price }}</h5>
                            {% if sale and product.discount_price %}
                            <h5>Discounted Price: ETB{{ product.discount_price }}</h5>
                            {% endif %}
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>

            <div class="product__pagination">
                <a href="#">1</a>
                <a href="#">2</a>
                <a href="#">3</a>
                <a href="#"><i class="fa fa-long-arrow-right"></i></a>
            </div>
        </div>
    </div>
    </div>
</section>
<!-- Product Section End -->


{% endblock %}

templates/create_post.html
<!-- templates/products/post_product.html -->
{% extends 'base.html' %}

{% block title %}Post a Product{% endblock %}

{% block header %}Product Posting Form{% endblock %}


{% block content %}

{% include 'nav.html' %}


    <!-- `this have to be reverse to the template dont forget it and also make ur own form types and styles this eill help u to change more and edit more to custmize make the fnalist part -->




    <div class="page-header" style="background: url(assets/img/banner1.jpg);">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="breadcrumb-wrapper">
                        <h2 class="product-title">Post you Ads</h2>
                        <ol class="breadcrumb">
                            <li><a href="/">Home /</a></li>
                            <li class="current">Post you Ads</li>
                        </ol>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <h1>Create Post</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Submit</button>
    </form>
</form>
{% endblock %}

templates/nav.html
{% load static %}


<header id="header-wrap">

    <div class="top-bar">
        <div class="container">
            <div class="row">
                <div class="col-lg-7 col-md-5 col-xs-12">

                    <ul class="list-inline">
                        <li><i class="lni-phone"></i> +251987654321</li>
                        <li><i class="lni-envelope"></i> <a href="http://preview.uideck.com/cdn-cgi/l/email-protection"
                                class="__cf_email__"
                                data-cfemail="5e2d2b2e2e312c2a1e39333f3732703d3133">[email&#160;protected]</a></li>
                    </ul>

                </div>
                <div class="col-lg-5 col-md-7 col-xs-12">
                    <div class="roof-social float-right">
                        <a class="facebook" href="#"><i class="lni-facebook-filled"></i></a>
                        <a class="twitter" href="#"><i class="lni-twitter-filled"></i></a>
                        <a class="instagram" href="#"><i class="lni-instagram-filled"></i></a>
                        <a class="linkedin" href="#"><i class="lni-linkedin-fill"></i></a>
                        <a class="google" href="#"><i class="lni-google-plus"></i></a>
                    </div>
                    <div class="header-top-right float-right">
                        <a href="{% url 'login' %}" class="header-top-button"><i class="lni-lock"></i> Log In</a> |
                        <a href="{% url 'users-register' %}" class="header-top-button"><i class="lni-pencil"></i>
                            Register</a>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <nav class="navbar navbar-expand-lg bg-white fixed-top scrolling-navbar">
        <div class="container">

            <div class="navbar-header">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#main-navbar"
                    aria-controls="main-navbar" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                    <span class="lni-menu"></span>
                    <span class="lni-menu"></span>
                    <span class="lni-menu"></span>
                </button>
                <a href="/" class="navbar-brand"><img src="{% static 'assets/img/logo1.png' %}" alt=""></a>
            </div>
            <div class="collapse navbar-collapse" id="main-navbar">
                <ul class="navbar-nav mr-auto w-100 justify-content-center">
                    <li class="nav-item">
                        <a class="nav-link dropdown-toggle" href="/">
                            Home
                        </a>

                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'myapp:shopgrid' %}">
                            Prodact List
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'myapp:trend' %}">
                            Trending Prodact
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'myapp:contact' %}">
                            Contacts
                        </a>
                    </li>
                </ul>
                {% if user.is_authenticated %}
                <div class="post-btn">
                    <a class="btn btn-common" href="{% url 'myapp:product_create' %}">
                        <i class="lni-pencil-alt"></i> Post an Ad
                    </a>
                </div>
                {% endif %}
            </div>
        </div>

        <ul class="mobile-menu">
            <li>
                <a class="active" href="/">
                    Home
                </a>
            </li>
            <li>
                <a href="{% url 'myapp:shopgrid' %}">Prodact List</a>
            </li>
            <li>
                <a href="{% url 'myapp:trend' %}">
                    Trending Prodact
                </a>
            </li>
            <li>
                <a href="{% url 'myapp:contact' %}">
                    Contact
                </a>
            </li>
            <li>
                {% if user.is_authenticated %}
                <div class="post-btn">
                    <a class="btn btn-common" href="{% url 'myapp:product_create' %}">
                        <i class="lni-pencil-alt"></i> Post an Ad
                    </a>
                </div>
                {% endif %}
            </li>



        </ul>

    </nav>
</header>

templates/payments.html
{% extends "base.html" %}

{% load static %}

{% block title %}Home{% endblock %}


{% block content %}

{% include 'nav.html' %}


<div class="page-header" style="background: url({% static 'assets/img/banner1.jpg' %});">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="breadcrumb-wrapper">
                    <h2 class="product-title">Payments</h2>
                    <ol class="breadcrumb">
                        <li><a href="#">Home /</a></li>
                        <li class="current">Payments</li>
                    </ol>
                </div>
            </div>
        </div>
    </div>
</div>


<div id="content" class="section-padding">
    <div class="container">
        <div class="row">
            <div class="col-sm-12 col-md-4 col-lg-3 page-sidebar">
                <aside>
                    <div class="sidebar-box">
                        <div class="user">
                            <figure>
                                <a href="#"><img src="{{ user.profile.avatar.url }}" alt=""></a>
                            </figure>
                            <div class="usercontent">
                                <h3>Hello!{{user.username}}</h3>
                            </div>
                        </div>
                        <nav class="navdashboard">
                            <ul>
                                <li>
                                    <a href="{% url 'myapp:Dash' %}">
                                        <i class="lni-dashboard"></i>
                                        <span>Dashboard</span>
                                    </a>
                                </li>
                                <li>
                                    <a href="{% url 'users-profile' %}">
                                        <i class="lni-cog"></i>
                                        <span>Profile Settings</span>
                                    </a>
                                </li>
                                <li>
                                    <a href="{% url 'myapp:my_ads' %}">
                                        <i class="lni-layers"></i>
                                        <span>My Ads</span>
                                    </a>
                                </li>
                                <li>
                                    <a href="{% url 'myapp:payment' %}">
                                        <i class="lni-wallet"></i>
                                        <span>Payments</span>
                                    </a>
                                </li>

                                <li>
                                    <a href="{% url 'myapp:Privacy' %}">
                                        <i class="lni-star"></i>
                                        <span>Privacy Settings</span>
                                    </a>
                                </li>
                                <li>
                                    <a href="/logout">
                                        <i class="lni-enter"></i>
                                        <span>Logout</span>
                                    </a>
                                </li>
                            </ul>
                        </nav>
                    </div>
                    <div class="widget">
                        <h4 class="widget-title">Advertisement</h4>
                        <div class="add-box">
                            <img class="img-fluid" src="{% static 'assets/img/img1.jpg' %}" alt="">
                        </div>
                    </div>
                </aside>
            </div>
            <div class="col-sm-12 col-md-8 col-lg-9">
                <div class="page-content">
                    <div class="inner-box">
                        <div class="dashboard-box">
                            <h2 class="dashbord-title">Payments</h2>
                        </div>
                        <div class="dashboard-wrapper">
                            <div class="row">
                                <div class="col-md-6 col-sm-6 col-sx-12">
                                    <H1>Comingsoon</H1>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    {% endblock %}

templates/product_edit.html
{% extends 'base.html' %}

{% block title %}Post a Product{% endblock %}

{% block header %}Edit Product{% endblock %}
{% load static %}
{% block content %}

{% include 'nav.html' %}

<div class="page-header" style="background: url({% static 'assets/img/banner1.jpg' %});">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="breadcrumb-wrapper">
                    <h2 class="product-title">Edit Product</h2>
                    <ol class="breadcrumb">
                        <li><a href="/">Home /</a></li>
                        <li class="current">Edit Product</li>
                    </ol>
                </div>
            </div>
        </div>
    </div>
</div>


<div id="content" class="section-padding">
    <div class="container">
        <div class="row">
            <div class="col-sm-12 col-md-4 col-lg-3 page-sidebar">
                <aside>
                    <div class="sidebar-box">
                        <div class="user">
                            <figure>
                                <a href="#"><img src="{{ user.profile.avatar.url }}" alt=""></a>
                            </figure>
                            <div class="usercontent">
                                <h3>Hello!{{user.username}}</h3>
                            </div>
                        </div>
                        <nav class="navdashboard">
                            <ul>
                                <li>
                                    <a href="{% url 'myapp:Dash' %}">
                                        <i class="lni-dashboard"></i>
                                        <span>Dashboard</span>
                                    </a>
                                </li>
                                <li>
                                    <a href="{% url 'users-profile' %}">
                                        <i class="lni-cog"></i>
                                        <span>Profile Settings</span>
                                    </a>
                                </li>
                                <li>
                                    <a href="{% url 'myapp:my_ads' %}">
                                        <i class="lni-layers"></i>
                                        <span>My Ads</span>
                                    </a>
                                </li>
                                <li>
                                    <a href="{% url 'myapp:payment' %}">
                                        <i class="lni-wallet"></i>
                                        <span>Payments</span>
                                    </a>
                                </li>

                                <li>
                                    <a href="{% url 'myapp:Privacy' %}">
                                        <i class="lni-star"></i>
                                        <span>Privacy Settings</span>
                                    </a>
                                </li>
                                <li>
                                    <a href="/logout">
                                        <i class="lni-enter"></i>
                                        <span>Logout</span>
                                    </a>
                                </li>
                            </ul>
                        </nav>
                    </div>
                    <div class="widget">
                        <h4 class="widget-title">Advertisement</h4>
                        <div class="add-box">
                            <img class="img-fluid" src="{% static 'assets/img/img1.jpg' %}" alt="">
                        </div>
                    </div>
                </aside>
            </div>
            <div class="col-sm-12 col-md-8 col-lg-9">
                <div class="row page-content">
                    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-7">
                        <div class="inner-box">
                            <div class="dashboard-box">
                                <h2 class="dashbord-title">Edit Ad Detail</h2>
                            </div>
                            <div class="dashboard-wrapper">
                                <form method="post" enctype="multipart/form-data">
                                    {% csrf_token %}
                                    <div class="form-group mb-3">
                                        {{ form.as_p }}
                                    </div>
                                    <button type="submit" class="btn btn-primary">Save Changes</button>
                                </form>
                            </div>
                        </div>
                    </div>
                    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-5">
                        <div class="inner-box">
                            <div class="tg-contactdetail">

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>
</div>

{% endblock %}